<!DOCTYPE html>
<html>
<head>
    <title>Unittest Results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2 class="text-capitalize">Unittest Results</h2>
                <p class='attribute'><strong>Start Time: </strong>2024-11-30 15:54:54</p>
                <p class='attribute'><strong>Duration: </strong>232 ms</p>
                <p class='attribute'><strong>Summary: </strong>Total: 5, Pass: 1, Fail: 1, Error: 3</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-10 col-md-10">
                <table class='table table-hover table-responsive'>
                    <thead>
                        <tr>
                            <th>__main__.TestHealthCareTranslationApp</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class='warning'>
                            <td class="col-xs-10">test_audio_input_failure</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ModuleNotFoundError: No module named 'st'</p><p style="color:maroon;">Traceback (most recent call last):
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1334, in patched
    with self.decoration_helper(patched,
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1316, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 429, in enter_context
    result = _cm_type.__enter__(cm)
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1389, in __enter__
    self.target = self.getter()
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1564, in <lambda>
    getter = lambda: _importer(target)
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1236, in _importer
    thing = __import__(import_path)
ModuleNotFoundError: No module named 'st'
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_successful_audio_transcription</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">AttributeError: 'dict' object has no attribute 'audio_bytes'</p><p style="color:maroon;">Traceback (most recent call last):
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "c:\Users\HP\Documents\PROGRAMMING\Healthcare Translation App using Generative AI\testing\Unit_TestCase.py", line 41, in test_successful_audio_transcription
    main()
  File "c:\Users\HP\Documents\PROGRAMMING\Healthcare Translation App using Generative AI\app.py", line 56, in main
    st.session_state.audio_bytes = audio_bytes
AttributeError: 'dict' object has no attribute 'audio_bytes'
</p>
                            </td>
                        </tr>
                        <tr class='success'>
                            <td class="col-xs-10">test_text_to_speech_conversion</td>
                            <td class="col-xs-1">
                                <span class="label label-success" style="display:block;width:40px;">Pass</span>
                            </td>
                            <td class="col-xs-1">
                            </td>
                        </tr>
                        <tr class='danger'>
                            <td class="col-xs-10">test_translation_with_gpt</td>
                            <td class="col-xs-1">
                                <span class="label label-danger" style="display:block;width:40px;">Fail</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">AssertionError: expected call not found.
Expected: text_area('Transcription', 'Hola mundo', label_visibility='collapsed')
Actual: text_area('Enter text to convert to speech')</p><p style="color:maroon;">Traceback (most recent call last):
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "c:\Users\HP\Documents\PROGRAMMING\Healthcare Translation App using Generative AI\testing\Unit_TestCase.py", line 64, in test_translation_with_gpt
    mock_translated_text_area.assert_called_with('Transcription', 'Hola mundo', label_visibility='collapsed')
  File "c:\Users\HP\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 907, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: text_area('Transcription', 'Hola mundo', label_visibility='collapsed')
Actual: text_area('Enter text to convert to speech')
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_ui_elements_presence</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">KeyError: <MagicMock name='selectbox()' id='2529739998112'></p><p style="color:maroon;">Traceback (most recent call last):
  File "c:\Users\HP\Documents\PROGRAMMING\Healthcare Translation App using Generative AI\testing\Unit_TestCase.py", line 71, in test_ui_elements_presence
    main()
  File "c:\Users\HP\Documents\PROGRAMMING\Healthcare Translation App using Generative AI\app.py", line 45, in main
    target_lang_code = supported_languages[selected_language]
KeyError: <MagicMock name='selectbox()' id='2529739998112'>
</p>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                Total: 5, Pass: 1, Fail: 1, Error: 3 -- Duration: 232 ms
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('td').on('click', '.btn', function(e){
                e.preventDefault();
                e.stopImmediatePropagation();
                var $this = $(this);
                var $nextRow = $this.closest('tr').next('tr');
                $nextRow.slideToggle("fast");
                $this.text(function(i, text){
                    if (text === 'View') {
                        return 'Hide';
                    } else {
                        return 'View';
                    };
                });
            });
        });
    </script>
</body>
</html